//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.12 at 10:29:26 AM EST 
//


package org.cloudgraph.state.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * A multi-level key/value map structure containing URI structures mapped
 * to UUIDs, mapped to integral 
 * sequence numbers, <b>unique</b> within a type, <b>unique</b> within a row.
 * @author Scott Cinnamond
 * @since 0.5.2
 *                 
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SequenceMap", propOrder = {
    "uris"
})
public class SequenceMap {

    @XmlElement(name = "URI", required = true)
    protected List<URIMap> uris;

    /**
     * Gets the value of the uris property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uris property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getURIS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link URIMap }
     * 
     * 
     */
    public List<URIMap> getURIS() {
        if (uris == null) {
            uris = new ArrayList<URIMap>();
        }
        return this.uris;
    }

}
