//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.12 at 10:29:26 AM EST 
//


package org.cloudgraph.state.model;

import java.util.HashMap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;



/**
 * 
 *             
 * Top level state container.
 * @author Scott Cinnamond
 * @since 0.5.2
 *             
 * 
 * <p>Java class for CloudGraphState complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CloudGraphState">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RowKeyMap" type="{http://www.cloudgraph.org/state}RowKeyMap" minOccurs="0"/>
 *         &lt;element name="SequenceMap" type="{http://www.cloudgraph.org/state}SequenceMap"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StateModel", propOrder = {
    "rowKeyMap",
    "sequenceMap"
})
@XmlRootElement(name = "StateModel")
public class StateModel {

    @XmlElement(name = "RowKeyMap")
    @XmlJavaTypeAdapter(RowKeyMapAdapter.class)
    protected HashMap<String, byte[]> rowKeyMap;
    @XmlElement(name = "SequenceMap", required = true)
    @XmlJavaTypeAdapter(SequenceMapAdapter.class)
    protected HashMap<QName, SequenceMapping> sequenceMap;

    /**
     * Gets the value of the rowKeyMap property.
     * 
     * @return
     *     possible object is
     *     {@link RowKeyMap }
     *     
     */
    public HashMap<String, byte[]> getRowKeyMap() {
    	if (this.rowKeyMap == null)
    		this.rowKeyMap = new HashMap<String, byte[]>();
        return rowKeyMap;
    }

    /**
     * Sets the value of the rowKeyMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link RowKeyMap }
     *     
     */
    public void setRowKeyMap(HashMap<String, byte[]> value) {
        this.rowKeyMap = value;
    }

    /**
     * Gets the value of the sequenceMap property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceMap }
     *     
     */
    public HashMap<QName, SequenceMapping> getSequenceMap() {
    	if (sequenceMap == null) {
    		sequenceMap = new HashMap<QName, SequenceMapping>();
    	}
        return sequenceMap;
    }

    /**
     * Sets the value of the sequenceMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceMap }
     *     
     */
    public void setSequenceMap(HashMap<QName, SequenceMapping> value) {
        this.sequenceMap = value;
    }

}
